import SwiftUI

/// Open-source acknowledgements.
///
/// Every dependency Lumina ships carries a licence that requires its notice to
/// travel with the binary — MIT and Apache-2.0 both say so explicitly — and the
/// app had no screen showing any of them. This is that screen.
///
/// The list is written by hand rather than generated, because there is no
/// build step that could generate it: `Package.resolved` isn't committed
/// (`Lumina.xcodeproj` is regenerated by XcodeGen), so nothing on disk
/// enumerates the resolved graph. Adding a dependency means adding a row here.
struct AcknowledgementsView: View {
    struct Component: Identifiable {
        let name: String
        let licence: String
        let url: String
        /// Why it's in the binary, in the user's terms.
        let role: String

        var id: String { name }
    }

    /// Direct dependencies declared in `project.yml`, plus the ephemeris
    /// library the backend computes every chart with. The last one is not
    /// linked into the app, but every number the app displays comes out of it,
    /// and its licence is the reason we can ship those numbers at all.
    static let components: [Component] = [
        Component(
            name: "RevenueCat",
            licence: "MIT",
            url: "https://github.com/RevenueCat/purchases-ios",
            role: "Runs subscriptions through the App Store."
        ),
        Component(
            name: "supabase-swift",
            licence: "MIT",
            url: "https://github.com/supabase/supabase-swift",
            role: "Exchanges your Sign in with Apple token for a session."
        ),
        Component(
            name: "OneSignal",
            licence: "MIT",
            url: "https://github.com/OneSignal/OneSignal-XCFramework",
            role: "Delivers push notifications."
        ),
        Component(
            name: "swift-crypto",
            licence: "Apache-2.0",
            url: "https://github.com/apple/swift-crypto",
            role: "Cryptography, via the libraries above."
        ),
        Component(
            name: "astronomy-engine",
            licence: "MIT",
            url: "https://github.com/cosinekitty/astronomy",
            role: "Computes every planetary position in your chart."
        ),
    ]

    var body: some View {
        List {
            Section {
                ForEach(Self.components) { component in
                    row(component)
                }
            } header: {
                Text("Built with")
            } footer: {
                sectionFootnote
            }
        }
        .listStyle(.insetGrouped)
        .scrollContentBackground(.hidden)
        .background(LuminaColors.parchment)
        .navigationTitle("Acknowledgements")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func row(_ component: Component) -> some View {
        Link(destination: URL(string: component.url) ?? URL(fileURLWithPath: "/")) {
            VStack(alignment: .leading, spacing: LuminaSpacing.xs) {
                HStack(alignment: .firstTextBaseline) {
                    Text(component.name)
                        .font(LuminaTypography.body)
                        .foregroundStyle(LuminaColors.inkBlack)
                    Spacer()
                    Text(component.licence)
                        .font(LuminaTypography.mono)
                        .foregroundStyle(LuminaColors.inkBlack.opacity(0.6))
                }
                Text(component.role)
                    .font(LuminaTypography.caption)
                    .foregroundStyle(LuminaColors.inkBlack.opacity(0.7))
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(component.name), \(component.licence) licence. \(component.role)")
        .accessibilityHint("Opens the project page")
    }

    private var sectionFootnote: some View {
        Text("Lumina is built on the work of others. Each name links to its project and licence. "
            + "The chart maths itself is ours, computed on our own service — no chart data is "
            + "bought from or sent to any of these.")
            .font(LuminaTypography.caption)
            .foregroundStyle(LuminaColors.inkBlack.opacity(0.7))
    }
}

#Preview {
    NavigationStack { AcknowledgementsView() }
}
