import SwiftUI

/// The two disclosures Lumina is obliged to make, in one place so the wording
/// can't drift between the screens that carry them.
///
/// Both were previously buried: the entertainment disclaimer existed only as a
/// footnote at the bottom of Settings → About, which nobody scrolls to, and
/// there was no AI disclosure at all even though the "Ask your chart" free-text
/// answer is generated by a language model. App Store Connect's age-rating
/// questionnaire now asks directly about in-app AI chat, and the answer has to
/// match what the app actually shows.
enum LuminaDisclosure {
    static let entertainment =
        "Lumina is for reflection and entertainment — not medical, legal, or financial advice."

    static let aiGenerated =
        "Written by AI from your computed chart. It can still get things wrong — trust yourself over it."
}

/// A quiet one-line entertainment disclaimer. Deliberately low-contrast: it
/// must be *present and legible*, not shouty.
struct EntertainmentDisclaimer: View {
    var body: some View {
        Text(LuminaDisclosure.entertainment)
            .font(LuminaTypography.caption)
            .foregroundStyle(LuminaColors.inkBlack.opacity(0.6))
            .frame(maxWidth: .infinity, alignment: .leading)
            .fixedSize(horizontal: false, vertical: true)
            .accessibilityLabel("Disclaimer. \(LuminaDisclosure.entertainment)")
    }
}

/// Attached to anything a language model wrote, with the report affordance
/// Apple expects next to user-facing generated content.
struct AIGeneratedNote: View {
    /// The generated text, quoted into the report so we can see what went
    /// wrong without asking the user to retype it.
    let reportedText: String

    @Environment(\.openURL) private var openURL
    @State private var mailUnavailable = false

    var body: some View {
        VStack(alignment: .leading, spacing: LuminaSpacing.xs) {
            HStack(alignment: .firstTextBaseline, spacing: LuminaSpacing.xs) {
                Image(systemName: "sparkles")
                    .foregroundStyle(LuminaColors.inkBlack.opacity(0.5))
                Text(LuminaDisclosure.aiGenerated)
                    .font(LuminaTypography.caption)
                    .foregroundStyle(LuminaColors.inkBlack.opacity(0.6))
                    .fixedSize(horizontal: false, vertical: true)
            }
            .accessibilityElement(children: .combine)
            .accessibilityLabel("AI generated. \(LuminaDisclosure.aiGenerated)")

            Button("Report this answer") { report() }
                .font(LuminaTypography.caption)
                .foregroundStyle(LuminaColors.celestialBlue)

            if mailUnavailable {
                Text("Couldn't open a mail app. Email \(FeedbackMail.address) and paste the answer.")
                    .font(LuminaTypography.caption)
                    .foregroundStyle(LuminaColors.error)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    private func report() {
        let body = "I'd like to report this answer:\n\n\(reportedText)\n\nWhat's wrong with it:\n"
        guard let url = FeedbackMail.mailtoURL(subject: "Report an AI answer", message: body) else {
            mailUnavailable = true
            return
        }
        openURL(url) { opened in
            mailUnavailable = !opened
        }
    }
}
