#!/usr/bin/env bash
# inject_env.sh — read .env.local, write secrets/Config.xcconfig.
#
# Run as an Xcode pre-build phase (declared in project.yml under
# `targets.Lumina.preBuildScripts`) and locally before `xcodegen generate`
# / opening Xcode. CI populates the same keys via GitHub Secrets and skips
# the .env.local read.

set -euo pipefail

ROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
ENV_FILE="${ROOT}/.env.local"
OUT_FILE="${ROOT}/secrets/Config.xcconfig"

mkdir -p "${ROOT}/secrets"

# Keys we expose to Info.plist via $(KEY) substitution. Keep in sync with
# project.yml's `info.properties` block.
KEYS=(
  ANTHROPIC_API_KEY
  ELEVENLABS_API_KEY
  ELEVENLABS_VOICE_ID
  REVENUECAT_API_KEY_IOS
  ONESIGNAL_APP_ID
  SUPABASE_URL
  SUPABASE_ANON_KEY
  SWISS_EPH_SERVICE_URL
  SWISS_EPH_API_SECRET
)

# Source .env.local if present. CI sets these as env vars instead.
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

{
  echo "// Auto-generated by scripts/inject_env.sh — DO NOT EDIT, DO NOT COMMIT."
  echo "// Source: \$ENV var or .env.local. Regenerate by re-running the script."
  echo ""
  for key in "${KEYS[@]}"; do
    value="${!key:-}"
    # Xcconfig is sensitive to '//' (treated as comment), '$' (variable), and trailing whitespace.
    # Empty values are written as `KEY =` so xcconfig parsing succeeds.
    printf '%s = %s\n' "${key}" "${value}"
  done
} > "${OUT_FILE}"

echo "inject_env.sh: wrote ${OUT_FILE}"
