#!/usr/bin/env bash
# inject_env.sh — read .env.local, write secrets/Config.xcconfig.
#
# Run as an Xcode pre-build phase (declared in project.yml under
# `targets.Lumina.preBuildScripts`) and locally before `xcodegen generate`
# / opening Xcode. CI populates the same keys via GitHub Secrets and skips
# the .env.local read.

set -euo pipefail

ROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
ENV_FILE="${ROOT}/.env.local"
OUT_FILE="${ROOT}/secrets/Config.xcconfig"

mkdir -p "${ROOT}/secrets"

# Keys we expose to Info.plist via $(KEY) substitution. Keep in sync with
# project.yml's `info.properties` block.
#
# ANTHROPIC_API_KEY is intentionally NOT here: LLM interpretation runs
# server-side (backend `/interpret`), so the key must never reach the app
# bundle — a client-side key is extractable from the IPA.
KEYS=(
  REVENUECAT_API_KEY_IOS
  ONESIGNAL_APP_ID
  SUPABASE_URL
  SUPABASE_ANON_KEY
  SWISS_EPH_SERVICE_URL
  SWISS_EPH_API_SECRET
)

# Source .env.local if present. CI sets these as env vars instead.
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

{
  echo "// Auto-generated by scripts/inject_env.sh — DO NOT EDIT, DO NOT COMMIT."
  echo "// Source: \$ENV var or .env.local. Regenerate by re-running the script."
  echo ""
  for key in "${KEYS[@]}"; do
    value="${!key:-}"
    # xcconfig treats '//' as a line comment ANYWHERE in the line, so writing
    # a URL raw silently truncates it:
    #
    #   SWISS_EPH_SERVICE_URL = https://lumina-ephemeris.fly.dev
    #                                 ^^ everything from here is a comment
    #
    # …leaving the literal value `https:`. That is non-empty, so
    # `BuildConfig.realValue` accepted it and the app failed EVERY backend
    # call at runtime — invisible in CI (simulator builds are expected to hit
    # `.missingConfiguration`) and only manifesting in the TestFlight/App
    # Store build. The comment here named the hazard and then did nothing
    # about it.
    #
    # `$()` is xcconfig's empty-variable-substitution idiom: it evaluates to
    # nothing, so `https:$()//host` parses as `https://host` while breaking up
    # the `//` token. Applied to every value, not just ones that look like
    # URLs, so a secret that happens to contain '//' survives too.
    escaped="${value//\/\//\$()\/\/}"
    printf '%s = %s\n' "${key}" "${escaped}"
  done
} > "${OUT_FILE}"

# Fail loudly rather than shipping a binary that can't reach its backend.
# A truncated URL is the failure this whole block exists to prevent, so
# verify the round trip instead of trusting it.
for key in "${KEYS[@]}"; do
  raw="${!key:-}"
  [[ -z "${raw}" ]] && continue
  written="$(sed -n "s/^${key} = //p" "${OUT_FILE}")"
  # Reverse the escape the way xcconfig would evaluate it.
  restored="${written//\$()/}"
  if [[ "${restored}" != "${raw}" ]]; then
    echo "inject_env.sh: ERROR — ${key} did not survive xcconfig escaping." >&2
    echo "  expected: ${raw}" >&2
    echo "  got:      ${restored}" >&2
    exit 1
  fi
done

echo "inject_env.sh: wrote ${OUT_FILE}"
